zymex22/Project-RimFactory-Revived

- Defs/ThingDefs_Buildings/Buildings_AutoMachineTool.xml
- Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs
- Source/ProjectRimFactory/AutoMachineTool/ModExtension_Testing.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/18
https://github.com/nullre/Project-RimFactory-Revived/issues/20
> test #18 #20

- Defs/ThingDefs_Buildings/Buildings_AutoMachineTool.xml
- Defs/ThingDefs_Buildings/Buildings_Transport.xml
- Source/ProjectRimFactory/AutoMachineTool/ITab_Bills2.cs
- Source/ProjectRimFactory/AutoMachineTool/PlaceWorker_Arrow.cs
- Source/ProjectRimFactory/AutoMachineTool/RS.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/26
https://github.com/nullre/Project-RimFactory-Revived/issues/28
> fix issues

- Source/ProjectRimFactory/Common/GridsUtilityExt.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/39
> performance improvement

- Source/ProjectRimFactory/Common/HarmonyPatches/RacePropertiesPatch.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/43
> fix drone behavior

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_GenRecipe_MakeRecipeProducts.cs
LWM Poison chance transpiler patch
> LWM Poison chance transpiler patch

- Languages/English/Keyed/AllKeyed_Settings.xml
- Settings/Settings.xml
- Source/ProjectRimFactory/Common/CompGlowerPulse.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/ModPatch.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModSettings.cs
- Source/ProjectRimFactory/ProjectRimFactory.csproj
https://github.com/nullre/Project-RimFactory-Revived/issues/46
> add mod settings

- Defs/ThingDefs_Buildings/Buildings_Hoppers.xml
- Source/ProjectRimFactory/Common/ModExtension_Settings.cs
- Source/ProjectRimFactory/ProjectRimFactory.csproj
- Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/47
> smart hopper pickup from ground

- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
https://github.com/nullre/Project-RimFactory-Revived/issues/53
> fix t3 miner exclude bug.

- Source/ProjectRimFactory/Common/CompEffecter.cs
- Source/ProjectRimFactory/Common/CompGlowerPulse.cs
- Source/ProjectRimFactory/Common/PRFMapComponent.cs
- Source/ProjectRimFactory/ProjectRimFactory.csproj
https://github.com/nullre/Project-RimFactory-Revived/issues/54
> fix deep drill issue

- Source/ProjectRimFactory/Industry/HarmonyPatches/Patch_CompCreatesInfestations_for_DeepQuarry.cs
Untested at the moment, alas - if it builds at all, it should be okay
> Stop DeepQuarry causing infestations when powered down

- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
If player had excluded bills, would throw errors - this should remove that danger
> Don't throw errors for null recipes on loading

- Defs/ThingDefs_Buildings/Buildings_Industry.xml
- Source/ProjectRimFactory/Common/CompEffecter.cs
- Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs
This is nullre's Tick() version.
> #55 changed to check fuel in quarry.

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Special/Building_Assembler_Learning.cs
Code back end for allowing CompRefuelables.
Note: If an assembler has both CompRefuelable and CompPowerTrader, both must be powered/fueled.
> T0 furnace

- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> Added Label to DSU

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
- Source/ProjectRimFactory/SAL3/Tools/ReflectionUtility.cs
May need to check if Line 311 & 312 can be Optimized.
> Fixed Bill starting with Thing Disallowed by Bill Resolves #122 & #104

- Source/ProjectRimFactory/AutoMachineTool/Building_BaseMachine.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BaseRange.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/ITab_PowerSupply.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #120 
Note:
I am not sure why we need to call it in this way. My current assumption is that is related to the loading progress and executes it at the correct time.
`this.MapManager.NextAction(somecall);`
`this.MapManager.AfterAction(5, somecall);`
> Fixed Power use on Load

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #137 
@zymex22 @lilwhitemouse I would recommend extensive testing additional before merging this since it alters the save process.
> Fixed Problems with Assemblers hirstory when created in an minified state

- Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs
@lilwhitemouse I am not sure if the was a special reason why the code was duplicated. But now it should be easier to maintain.
Some comments died in the process, we can bring them back if needed.
resolves #131
> Removed Duplicate Code & Fixed Miners working while off

- Source/ProjectRimFactory/Drones/DroneBackstories.cs
resolves #151 
The Check will avoid an error as described in #151.
> fixed #151 by only adding a Backstory if it is unique

- Source/ProjectRimFactory/Common/CompSecondLayer.cs
> #160 Added the Code to PRF

- Source/ProjectRimFactory/AnimalStation/Building_CompHarvester.cs
resolves #117 
Added the code to support the range slider for the animal stations.
> Added code to support the range slider

- Languages/English/Keyed/AllKeyed_SAL3.xml
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #157 
Added the logic for the switch.
> Added the logic for the switch

- Source/ProjectRimFactory/Drones/Pawn_Drone.cs
resolves #152 
Cherry pick of #80
> Fixed #152 by setting the Destroyed flag for the pawn.

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
Added Update function to the default Label
> Added update on load to the Designator default label

- Source/ProjectRimFactory/Drones/Building_DroneStationRefuelable.cs
This should fix the reported Issue
> fixed the issue where refuelable stations with too few Drones

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
resolves #204 
Code copied for assembler.
> Fix for missing power

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
- Source/ProjectRimFactory/SAL3/Tools/ReflectionUtility.cs
@zymex22  This is ready to merge.
This is the code we (@lilwhitemouse  and myself) initially provided to fix #54 in PR133
For some unknown reason we did not merge that PR but closed the issue as resolved.
This PR should finally fix the issue.
> Added code from PR133 In relation to #54

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
- Source/ProjectRimFactory/Drones/Building_DroneStationRefuelable.cs
resolves #205 
@zymex22 please test before merge.
> that should fix it

- Source/ProjectRimFactory/Drones/ITab_DroneStation.cs
- Source/ProjectRimFactory/Drones/Pawn_Drone.cs
> fixed #212

- Source/ProjectRimFactory/Drones/DroneSkills.cs
- Source/ProjectRimFactory/Drones/Pawn_Drone.cs
@zymex22 That should fix the ITab update Issue
> TIL you cant pass Propertys by ref

- Defs/ResearchProjectDefs/ResearchProjects_Common.xml
increased cost of a few since the side-techs are 1000-3000. redid all text and tech names.
> total Flavour text rewrite + minor balance changes

- Source/ProjectRimFactory/CultivatorTools/Building_CellIterator.cs
- Source/ProjectRimFactory/CultivatorTools/Building_RadialCellIterator.cs
- Source/ProjectRimFactory/CultivatorTools/Building_SquareCellIterator.cs
> removed unused variable causing #226

- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/ITab_PowerSupply.cs
resolves #233 
as per usual @zymex22 please test before you merge
> resolved sound Bug & allowed more speed settings

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #202 
@zymex22 Good luck testing this for real.
I am fairly certain that it will work. 
But i only tested it by destroying the only power source
> likely fixed #202 by adding an active check when showing effects

- Defs/PawnKindDefs_AssemblerPawns/PawnKindDefs_AssemblerPawns.xml
Resolve #209 
not sure if it will fix health issues though, but dunno if thats important? can there be any bad effects from that?
> should fix #Issue209

- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/AutoMachineTool/GraphicExtraData.cs
- Source/ProjectRimFactory/AutoMachineTool/Graphic_LinkedConveyorWall.cs
merge if you think its ready @lilwhitemouse 
i have build and tested and totally solved problem with transitions yay!
> Lwm belts fix

- Source/ProjectRimFactory/Drones/Building_DroneStationRefuelable.cs
> fixed #256 

- Defs/ThingDefs_Buildings/Buildings_Assemblers.xml
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Special/Building_Assembler_Learning.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Special/ModExtension_LearningAssembler.cs
> initial implementation for #228

- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
> fixed #266 by adding a duplicate defName Check.

- Languages/English/Keyed/AllKeyed_SAL3.xml
- Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs
- Source/ProjectRimFactory/Common/PRFGameComponent.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
Creating the Pull request in Preparation. **Not ready to merge!**
as of now it adds the items to the total Counts. Allowing the use of produce till x Amount even if the output is blocked.
> resolves 168

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/ITab_ProductionSettings.cs
resolvs #241 
should be ready.
> Added button to rotate the input Cell Range (Only visible if nessesary)

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
@zymex22 this should resolve the zone update issues.
I removed one of my old Optimization attempt as it was pointless.
> fixed the the zone update issue by removing pointless optimization

- Source/ProjectRimFactory/AutoMachineTool/Building_Base.cs
- Source/ProjectRimFactory/CultivatorTools/Building_Cultivator.cs
resolves #285 
resolves #284 
Fixed the null ref
> fixed null error for miner & Cultivator

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/PlaceWorker_NaturalWall.cs
resolves #290 
FYI @Riderfighter
> Issue290 - Placeworker for T0 miner

- Defs/ThingDefs_Buildings/Buildings_Industry.xml
- Defs/ThingDefs_Buildings/Buildings_Miners.xml
- Settings/SpecialSculpture.xml
- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
- Source/ProjectRimFactory/Common/Debug.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/CompArt_GenerateImageDescription.cs
- Source/ProjectRimFactory/Common/ModExtension_BonusYield.cs
- Source/ProjectRimFactory/Common/ModExtension_ModifyProduct.cs
- Source/ProjectRimFactory/Common/ModExtension_ModifyProduct.txt
- Source/ProjectRimFactory/Common/PRFGameComponent.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModSettings.cs
- Source/ProjectRimFactory/Common/SpecialSculpture.cs
- Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
Resolve #248 
merge when ready @lilwhitemouse
> Extend BonusYield DefModExtension for general use

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
> #297 Fixed flickering drones if power is off

- Source/ProjectRimFactory/Common/ITab_ProductionSettings.cs
> changed values to be more reasonabel

- Source/ProjectRimFactory/AutoMachineTool/Ops.cs
- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/Util.cs
> #295 resolved issue by counter acting the base game function

- Source/ProjectRimFactory/Common/PlaceWorker_NaturalWall.cs
resolves #308  
Please note that this issue with Replace Stuff needs to by fixed by Replace Stuff (for us this is only a visual issue)
> This should resolve the issue with the T0 Mine

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
> fixed #311 by checking if the line is empty before drawing it

- Source/ProjectRimFactory/AutoMachineTool/PlaceWorker_PullerCellsHilight.cs
> #319 fixed issue with bp

- Source/ProjectRimFactory/AutoMachineTool/Building_HarvestPuller.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs
- Source/ProjectRimFactory/Common/GatherThingsUtility.cs
resolves #322 
With this Pullers shod be able to pull from Storage Zones & DS
also updates `Option<Thing>` to just use `Thing`
FYI @lilwhitemouse
> fixed #322 by expanding the search for things

- Defs/ThingDefs_Buildings/Buildings_Logistics.xml
> #326 Added the missing refs to the comp (maybe needs balancing)

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/PlaceWorker_NaturalWall.cs
resolves #338 
Changed the placeworker to requiere smoothed rock in case Replace stuff is installed
Added seperate placment not possibel info in case Replace Stuff is installed
> Added fix for mines being placabel ontop of each other

- Source/ProjectRimFactory/AutoMachineTool/Building_HarvestPuller.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs
resolves #352 
@zymex22 pls test.
**This Update is relevant for Lite & Core**
> Updated code to save takeSingleItems

- Source/ProjectRimFactory/Common/HarmonyPatches/HexCapacitorPatch.cs
> #354 added Harmony Patch for the Need Batteries Aleart

- Patches/Drill patches/Cupro_Stones.xml
> Fixed the same mistake in cupro stones patch

- Source/ProjectRimFactory/Drones/AI/JobGiver_DroneMain.cs
Another small improvement for Drone performance
_expecting the Fluffys WorkTab overhead to reduce by ~25%_
> #217 removed unnessesary call to SetPriority

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
- Source/ProjectRimFactory/Common/PRFMapComponent.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
fix (partially) #359
Better would be to only do the HarmonyPatch if there are any defs that would actually use it.
> Faster patch, should significatnly speed up some scenarios

- Source/ProjectRimFactory/Storage/UI/ITab_Items.cs
resolves the issue with the items ind the DSU
https://www.youtube.com/watch?v=4mNNb0OyzlA&feature=youtu.be
> refresh the Search results if a diffrent DSU is selected

- Source/ProjectRimFactory/AutoMachineTool/Building_Slaughterhouse.cs
> fixed Slaugher house input rotation

- Source/ProjectRimFactory/CultivatorTools/Building_Cultivator.cs
> #376 Cultivators nolonger place items ontop of themselfs

- Languages/English/Keyed/AllKeyed_AutoMachineTool.xml
- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_Slaughterhouse.cs
- Source/ProjectRimFactory/AutoMachineTool/ITab_Slaughterhouse.cs
resolves #378 
Testing requires additional mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856 `Aerofleets`
_**Warning: Explosive**_
> #378 Added support for genderless animal Slaughter Settings

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
> this should fix #380

- Source/ProjectRimFactory/Storage/UI/ITab_Items.cs
> #363 fixed ITab issue if no pawns are pressent

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BaseRange.cs
might fix #383 and other similar reports that we could not reproduce
> #387 ensured that the Input zone gets updated

- Source/ProjectRimFactory/AutoMachineTool/Graphic_WallLight.cs
resolves #396 
ready to merge if the issue is resolved
> #396 resolved issue by checking if Placeworkers is null

- Source/ProjectRimFactory/AutoMachineTool/ITab_Slaughterhouse.cs
resolves #399 
@zymex22 Ready to merge after test
> #399 now supporting Screen hights above ~744

- Source/ProjectRimFactory/SAL3/Things/Building_RecipeHolder.cs
> #401 Saved the Quered Recipes

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
> #409 resolved issue by null checking workingEffect

- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
- Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
- Source/ProjectRimFactory/Storage/UI/Dialog_RenameMassStorageUnit.cs
> #370 added rename functionality to the IO Ports

- Languages/English/Keyed/AllKeyed_AutoMachineTool.xml
- Source/ProjectRimFactory/AutoMachineTool/Building_Base.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BeltSplitter.cs
> Lwm splitters

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_DSU_OrbitalTrade.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnitPowered.cs
resolves #384 
@zymex22  should be ready for merge after a Test.
@lilwhitemouse can you have a quick glance at my Transpiler just to make sure i did not do anything foolish there.
> #384 Made DSU's act as Trade Beacons

- Source/ProjectRimFactory/Industry/Building_FuelingMachine.cs
will fix #422 from our side but SOS2 Also needs to update their patch for the torpedo launchers.
> #422 fixed issue with FuelingMachine in PRF-Lite

- Source/ProjectRimFactory/AutoMachineTool/PlaceWorker_PullerCellsHilight.cs
> #416 fixed null ref in Puller Placeworker

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/PlaceWorker_NaturalWall.cs
> #429 removed Incompatibility handling for Replace Stuff

- Source/ProjectRimFactory/AutoMachineTool/Building_Base.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/GatherThingsUtility.cs
- Source/ProjectRimFactory/Common/GridsUtilityExt.cs
- Source/ProjectRimFactory/Common/PlaceThingUtility.cs
- Source/ProjectRimFactory/Common/PlaceWorker_GrowZonePuller.cs
- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_SmartAssembler.cs
- Source/ProjectRimFactory/SAL3/Things/Building_RecipeHolder.cs
- Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs
> #314 added inital out of Bounds checks

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
> #390 added Gizmo to Create Stockpile

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchIOReservation.cs
resolves #389 
**Test's should be done for:**
--> Expecting a standing job in the worst case
If the tests run fine this can be merged
> Issue389 Multiple Users for one IO Port

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/ModExtension_ModifyProduct.cs
- Source/ProjectRimFactory/Common/PRFGameComponent.cs
- Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs
resolves #335 
@zymex22 is `Weight` understandable for a user or should we present it differently? if so suggestions?
otherwise ready to merge
> #335 added Info to the Description of the Building

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_DynamicBillGiver.cs
Fixes an out of bounds error that was missed in #314 
not ready for merge / pending initial tests
> #314 Fixed another out of bounds error - for assemblers

- Defs/ResearchProjectDefs/ResearchProjects_Batteries.xml
Changes the descriptions of the LargeBatteries and VeryLargeBatteries research projects to correspond to an update moving 64K batteries from Large to Very Large.
> Resolve #444

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
resolves #449 
Tests by `Madman666`(Discord) and myself show a significant Performance Improvement.
FYI: @lilwhitemouse
@zymex22 Ready for Testing & Merge.
_This is relevant for both Core & Lite_
> #449 Improved Performence of Patch_Building_Storage_Accepts

- Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs
Resolves #443 
Ready for test & Merge
> #443 removed unintended else that caused this issue

- Languages/English/Keyed/AllKeyed_Other.xml
- Source/ProjectRimFactory/Common/RS.cs
- Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
Resolves #394 
Ready for test & merge
> #394 Added toggle Gizmo to enable & disable Frobid on Placement

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #470 
@zymex22 ready for test & merge
> #470 fixed SAL & Assemblers stealing items

- Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs
resolves #474 
@zymex22 ready for test and merge
> #474 added removal of requiredResearchFacilities for the Lite Mode

- Source/ProjectRimFactory/Storage/UI/ITab_Items.cs
> #481 added aditional canEquip checks

- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnitPowered.cs
- Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
@zymex22 Please do some tests before merging.
this changes quite a bit of logic and i want to make sure there are no unintended side effects.
> #483 cached ModExtentions and optimized duplicate calculations

- Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs
resolves #488 
ready for test and merge.
> #488 added support for Architect Icons when using the Lite mode

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
hopefully resolves #491 (as the issue can't be reproduced)
currently marked as draft as i could not test it myself.
> added check for splitof thing count

- Source/ProjectRimFactory/Common/GatherThingsUtility.cs
resolves #490 
ready for test and merge
> #490 prevents Prf Buildings from stealing items form building frames

- Source/ProjectRimFactory/AutoMachineTool/Graphic_Two.cs
resolves #508 
This implementations always returns the NS Graphic (rotation is not provided).
but it seems to look fine to me.
> #508 implements GetColoredVersion

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/AutoMachineTool/GenRecipe2.cs
- Source/ProjectRimFactory/AutoMachineTool/Ops.cs
> #511 added code to handle precepts

- Source/ProjectRimFactory/Storage/UI/Dialog_OutputMinMax.cs
This should resolve the issue noted at https://github.com/zymex22/Project-RimFactory-Revived/pull/503#pullrequestreview-758269075
ready for test and merge
> added input grace period as described in the #503 pr

- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
- Source/ProjectRimFactory/Common/PRFMapComponent.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> #513 added support for more then one IHideItem for any pos

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
> #506 fixed issue by activating things again

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
resolves #540 
ready for test and merge
> #540 fixed arg null ref error if map is null

- Source/ProjectRimFactory/Storage/Building_MassStorageUnitPowered.cs
resolves #538 
ready for test and merge
> #538 fixed null ref issue when placing DSU ontop of spawned items

- Languages/English/Keyed/AllKeyed_Help.xml
This has absolutely no functional impact of any kind, but it will stop whiny `Visual Exceptions` users from complaining.
With that change our files will once again be compatible with SGML.
> Added back SGML support

- Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
resolves #530
Ready for Test and Merge
> #530 improved performence of IO Outputs

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchPage_SelectScenarioPreOpen.cs
- Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs
resolves #549 
Ready for test and merge
> #549 removed Factory Entrepreneur Scenario if Lite mode is enabled

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
- Source/ProjectRimFactory/Common/PRFMapComponent.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> Updated the patch's system to make it faster

- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
> resolved mod conflict with Technology Blueprints & Reverse Engineering

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
> #568 Prevents SAL Deep drilling despite forbidden setting

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
- Source/ProjectRimFactory/ProjectRimFactory.csproj
> #570 fixed SAL Benches losing Bills on Uninstall

- Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs
> #567 added regex check to not match unintended recipies

- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> #585 resolved issue by hiding all cells

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_BillStack_AddBill.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/SaveStorageSettings_Patch.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
> #195 added support for Save Storage on drills

- Source/ProjectRimFactory/AutoMachineTool/Building_BaseRange.cs
> #542 SAL Autominer can now work on recipes that requier no ingridiants

- Patches/Drill patches/Kura's Extra Stone.xml
- Patches/Recipes_Stone_Mining.xml
- Patches/Stone_Mining.xml
(K) Extra Stone(w/Cupro's Textures) mod patch files added for chunk omission on miners and ability to mine them in the stone mine.
> Mod Patch Submission

- Defs/ThingDefs_Buildings/Buildings_SAL_Like.xml
> #583 Fixed SAL Color

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
> #604 resolved issue by deepsaving ingredients

- Source/ProjectRimFactory/Common/Command_ActionRightLeft.cs
- Source/ProjectRimFactory/Common/CompOutputAdjustable.cs
> #601 added Right and Leftclick Actions

- Defs/ThingDefs_Buildings/Buildings_Cultivators.xml
- Defs/ThingDefs_Buildings/Buildings_Industry.xml
- Defs/ThingDefs_Buildings/Buildings_SAL_Like.xml
- Languages/English/Keyed/AllKeyed_Help.xml
- Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs
- Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
- Source/ProjectRimFactory/Common/ModExtension_ModifyProduct.cs
- Source/ProjectRimFactory/Common/ModExtension_Skills.cs
- Source/ProjectRimFactory/Common/PRFGameComponent.cs
- Source/ProjectRimFactory/Common/UpdateThingDescriptions.cs
- Source/ProjectRimFactory/CultivatorTools/Utilities.cs
- Source/ProjectRimFactory/Drones/DefModExtension_DroneStation.cs
- Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs
- Source/ProjectRimFactory/SAL3/Things/Assemblers/Special/ModExtension_LearningAssembler.cs
- Source/ProjectRimFactory/SAL3/Things/CompRecipeImportRange.cs
Styling Review and feedback needed.
_Pictures are available in the Issue_
resolves #436
> Auto Description

- Source/ProjectRimFactory/Common/ConditionalPatchHelper.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> #616 removed Draw Patch

- Source/ProjectRimFactory/Common/HarmonyPatches/FridgePowerPatchUtil.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_CompRefrigerator_CompTickRare.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_Patch_GameComponentTick_Postfix.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnitPowered.cs
> #613 added patches to correctly update Power use

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_FoodUtility_SpawnedFoodSearchInnerScan.cs
> #625 resolves issue where Replimat is incorrectly moved

- Source/ProjectRimFactory/AutoMachineTool/Building_HarvestPuller.cs
- Source/ProjectRimFactory/Common/PlaceWorker_GrowZonePuller.cs
> #632 added support for special Grow-Zones of VPE - More Plants

- Source/ProjectRimFactory/Storage/Building_ColdStorage.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
- Source/ProjectRimFactory/Storage/StorageOutputUtil.cs
> #635 added check to prevent dropping item in same conatiner

- Patches/RimFridge.xml
- Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
Added KV Rimfridge fork and KV Save Storage Fork and ResearchPowl (forked from ResearchPal)
> Potential 1.4 updates for mods

- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
Adjusts for new class.
Closes #645
> Fix for Class Change

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
- Source/ProjectRimFactory/SAL3/Tools/ReflectionUtility.cs
> #650 prevented additional cases where skills could be disabled

- Source/ProjectRimFactory/Storage/UI/ITab_IOPortStorage.cs
- Source/ProjectRimFactory/Storage/UI/ITab_Items.cs
> #657 improved the ITab visibility checks

- 1.2/Defs/ScenarioDefs/Scenarios_PRF.xml
- 1.3/Defs/ScenarioDefs/Scenarios_PRF.xml
- Defs/ScenarioDefs/Scenarios_PRF.xml
I was bothered by the grammar in the scenario, so I fixed it (removed some extra words, reworded some sentences so it flows better).
I also ran a spellchecker on the scenario files!
> Better grammar for scenario (and spelling correction)

- Languages/English/Keyed/AllKeyed_CT.xml
- Source/ProjectRimFactory/Common/CommonColors.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
- Source/ProjectRimFactory/Common/SeedsPleaseSupport.cs
- Source/ProjectRimFactory/CultivatorTools/Building_Cultivator.cs
- Source/ProjectRimFactory/CultivatorTools/CultivatorDefModExtension.cs
- Source/ProjectRimFactory/CultivatorTools/Utilities.cs
> added support for SeedsPleaseLite

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
> #656 Reservation Update for SAL WorkBench

- Source/ProjectRimFactory/Common/HarmonyPatches/DronePatch.cs
> #661 fixed issue where trapped drones would crash the game

- Defs/ThingDefs_Buildings/Buildings_Storage.xml
> #652 renamed Cold Storage Unit to Archival Storage Unit

- Source/ProjectRimFactory/Common/HarmonyPatches/RacePropertiesPatch.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
> #668 removed obsolete Locks2 Patch

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_GenRecipe_MakeRecipeProducts.cs
resolves #680 
Include a Transpiler that Prevents Drones for being treated as mechanoids
> #680 fixed issue where drone Skills where ignored

- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyorUGConnector.cs
Baseline Paused Draw
Baseline Speed 3 Draw
New Paused
New Speed 3
> Optimized DrawCarried

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
- Source/ProjectRimFactory/Industry/Building_FuelingMachine.cs
- Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs
> #694 fixed issue by setting parameter to false

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
closes #690 
Might need further Tests for compatibility
> Changed how Drones Generate #690

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
> #700 set Relations to prevent Ido Related issue for some Memes

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
resolves #699
reopens #678 for rework
> Hotfix for Issue with IO Port Limit

- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
resolves #678 
In my testing I did not observe any haul loops when using limits
> #678 Optimized Patch_Building_Storage_Accepts

- Source/ProjectRimFactory/Drones/AI/JobGiver_DroneMain.cs
- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
- Source/ProjectRimFactory/Drones/Building_WorkGiverDroneStation.cs
resolves #712 
Compiled dll
[ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/11630385/ProjectRimFactory.zip)
> #712 added further drone Optimizations

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
> resolved #716 by checking the Type

- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
resolves #723 
Note `speedy` confirmed that this solve issue.
Please note that this does not fix the cause, as that is still unknown.
> #723 Added Error handeling checks

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_SaveStorageSettings_Patch_Building_GetGizmos.cs
> Fixed issue removing SaveStorage Gizmos from other buildings

- Source/ProjectRimFactory/Common/ConditionalPatchHelper.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
- Source/ProjectRimFactory/Common/ProjectRimFactory_ModSettings.cs
> #721 removed obsolete patch

- Source/ProjectRimFactory/AutoMachineTool/Building_BaseLimitation.cs
- Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs
- Source/ProjectRimFactory/AutoMachineTool/IProductLimitation.cs
- Source/ProjectRimFactory/AutoMachineTool/MapTickManager.cs
- Source/ProjectRimFactory/Common/ILimitWatcher.cs
- Source/ProjectRimFactory/Common/ITab_ProductionSettings.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> #718 Optimized the Puller limit Calculation

- Defs/JobDefs/JobDefs_Static.xml
- Source/ProjectRimFactory/AutoMachineTool/JobDriver_StaticJob.cs
resolves #732 
Dll for convenience: [ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/12418903/ProjectRimFactory.zip)
> #732 added Jobdef and driver

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
> #735 added support for non sustainer workingSounds

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
resolves #737 
Build for convenience:  
[ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/12706364/ProjectRimFactory.zip)
Replace dll in `Steam\steamapps\workshop\content\294100\2033979700\Assemblies`
> Fixed Issue with Disappearing drones

- Settings/Settings.xml
> Fixed Issue where the patch would target non DSU type Storage

- Source/ProjectRimFactory/Common/PRFDefOf.cs
- Source/ProjectRimFactory/Common/PRFGameComponent.cs
- Source/ProjectRimFactory/SAL3/Tools/ReflectionUtility.cs
resolves #610 
This Resolves the issue using C#.
This has the Added benefit that it will work with any mod altering what Things can be Minified
> #610 Added Dynamic Check if Trader Items are mineable

- Patches/Drones/SaveOurShip2.xml
> Added Support for new SOS2 Build

- Source/ProjectRimFactory/AutoMachineTool/Building_AutoMachineTool.cs
> added Null ref checks for SAL

- Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
> #659 fixed error on load by removen null bill billreport

- Source/ProjectRimFactory/SAL3/Things/Building_RecipeHolder.cs
> Fixed Issue by Blocking Bill_Mech on Recipe DB

- Defs/ThingDefs_Buildings/Buildings_Misc.xml
> Fixed issue where sun wall lamp's where on during the rest time

- Defs/ThingDefs_Buildings/Buildings_Drones.xml
- Defs/ThingDefs_Buildings/Buildings_Misc.xml
> added darklight toggle

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
> fixed issue where drones would not notice a change to forbidden

- Defs/ThingDefs_Buildings/Buildings_Logistics.xml
- Languages/English/Keyed/AllKeyed_SAL3.xml
- Source/ProjectRimFactory/Common/IPickupSettings.cs
- Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs
- Source/ProjectRimFactory/SAL3/Things/ITab_SmartHopper.cs
> Added finer selection options to the Smart Hopper

- Source/ProjectRimFactory/Common/PRFGameComponent.cs
Actual fix for #610
tbh i have no idea what was wrong with me when I wrote 42e742e691b3be25a9651147a82b7fa8abe53ae4 and merged #752 
We want to check if a building is Minifiable NOT if it can be mined....
> Actually check if trader buildings are Minifiable

- Source/ProjectRimFactory/Drones/DroneBackstories.cs
> resolved Character Editor incompatibility

- Source/ProjectRimFactory/Common/ConditionalPatchHelper.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
> Fixed "Started 10 Jobs" Job Errors

- Source/ProjectRimFactory/Common/HarmonyPatches/SAL_CanReservePatch.cs
resolves #780
hopefully fixed an anomaly issue
fixed issue with Alert_NoBabyFeeders
Needs Confirmation that https://github.com/zymex22/Project-RimFactory-Revived/issues/780#issuecomment-2106211843 works for the DLC
> #780 Fixed Null ref in CanReservePatch

- Defs/ScenarioDefs/Scenarios_PRF.xml
> Fixed Raid starting Instantly

- Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs
- Source/ProjectRimFactory/Common/GatherThingsUtility.cs
resolves #792 
added support to allow entrances and UG belts if needed
> Resolved Issue where Pullers can't pull from entrances and exits for UG Belts

- Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs
> Prevented UG Belts from receiving items from standard Above-ground Buildings

- Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
> fixed issue by ensuring correct settings are loaded

- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
> Draw Update

- Source/ProjectRimFactory/Common/HarmonyPatches/SetPositionPatch.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
Should also cut down on the ItemCounts error
> DSU Performance Improvements 

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
Added Handling in case the map is null for the SAL Release.
> SAL Release reduced the impact of a null map

- Source/ProjectRimFactory/AutoMachineTool/Building_BaseLimitation.cs
- Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
> Fixed issue where pawn Access Patch was affecting Pullers

- Source/ProjectRimFactory/Common/HarmonyPatches/Patch_Thing_TryAbsorbStack.cs
- Source/ProjectRimFactory/Storage/Building_MassStorageUnit.cs
Needs Testing
Might resolve #834
> Added Absorb Patch for Item counts

- Patches/Stone_Patches/Extra_Stone.xml
> updated def names for `[K]Extra Stone`

- Languages/Russian/DefInjected/ThingDefs/Buildings_Storage.xml
Fixes https://github.com/zymex22/Project-RimFactory-Revived/issues/832
> fix(typo): Typo in Russian translation

- Defs/ThingDefs_Buildings/Buildings_Cooking.xml
- Defs/ThingDefs_Buildings/Buildings_SAL_Like.xml
- Defs/ThingDefs_Buildings/Buildings_Storage.xml
> fixed weather overlay

- Patches/Drones/Vanilla_Fishing_Expanded.xml
- Patches/Food_Patches/Fermentation_VE.xml
- Patches/Food_Patches/Recipes_Fermentation_VBE.xml
> fixed updated defs and availability

- Defs/ThingDefs_Buildings/Buildings_Storage.xml
> added missing blueprintClass

- Source/ProjectRimFactory/Drones/Building_DroneStation.cs
> #871 Hoxtfix for NULL extensison on load

- Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs
> Fixed null ref on Destroyed SAL target

- Defs/ThingDefs_Buildings/Buildings_Common.xml
> fixed reaserch terminal building type

- Patches/Fishing/00_OnlyIfFish.xml
- Patches/Fishing/Odyssey.xml
renamed patch file for load order
resolves #886
> added Odyssey Fish support
