zymex22/Project-RimFactory-Revived

Defs/ThingDefs_Buildings/Buildings_Transport.xml, Source/ProjectRimFactory/AutoMachineTool/Building_HarvestPuller.cs, Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs, Source/ProjectRimFactory/AutoMachineTool/ITab_PullerFilter.cs
resolves #55 search bar on the puller storage UI
This adds the the RSA Support by using the Default Storage Tab
Also adds the Copy & Paste Gizmos to replace the now missing "Select copy from" Button
Notes:
`Source/ProjectRimFactory/AutoMachineTool/ITab_PullerFilter.cs` --> Just commented out for now we can probably just delete it entirely. 
`Source/ProjectRimFactory/AutoMachineTool/Building_ItemPuller.cs` Line 47 - 48: Thats probably not how I'm supposed to prevent that NullReference Error.
=> RSA Support & Added Copy & Paste Gizmos to the Item Puller

Source/ProjectRimFactory/AutoMachineTool/Graphic_Linked2.cs
This fixes the Belt uninstall / Reinstall Issues.
Known side effect:
- There is no image for the Minified Thing
Maybe we should resolve that one before merging it.
=> Fixed ProjectRimFactory.AutoMachineTool.Graphic_Linked2.DrawWorker

Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
resolves #165 
Adds a call to consume fuel per tick if all of the following conditions are met:
- Building uses fuel
- Building is active / has fuel
- Building is working on a bill
TODO:
=> Added the needed code to consume fuel

Source/ProjectRimFactory/Common/CompPowerWorkSetting.cs
resolves #234 
@zymex22 This should resolve the issues.
if the building in not symmetrical I'm using the largest direction for the size calculation
=> fixed CircleRange ignoring building size

Source/ProjectRimFactory/Drones/Building_DroneStation.cs, Source/ProjectRimFactory/Drones/Building_DroneStationRefuelable.cs
Bases on some feedback from @lilwhitemouse I moved `CompRefuelable` to Building_DroneStation
The init of `CompRefuelable refuelableComp` is also moved to `public override void ExposeData()`
based on some Analysis of RW Code this is the earliest point possible to load Components _(even for Minified things)_.
@zymex22 small second test cant hurt. this should be better then the initial fix of #256 (provided with #260 )
=> enhanced fix for #256

Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs
resolves #274 
Note:
While fixing this issue i noticed that the game counts some things (for example Art) differently.
This mean that the do work until is not respecting the internal storage of assemblers.
=> fixed error by adding proper Checks

Source/ProjectRimFactory/Common/HarmonyPatches/UpdateResourceCountsPatch.cs
This resolves an oversight in the fix(#271) for #168
Art is not counted by `UpdateResourceCounts` but is instead Count via `RecipeWorkerCounter.CountProducts(bill)`
This adds a Harmony Patch so that things counted by `CountProducts` include things in the Assembler Queue.
Added @lilwhitemouse to check if the Patch is fine or if it should be enhanced.
=> Added support for the Art Counter

Source/ProjectRimFactory/Drones/Building_DroneStation.cs
resolves #336 
Will ensure that Zones are deleted on spawn. preventing unused Zones from clogging the save file.
_Note: this will not delete already existing zones. for affected users a manual cleanup of the save file is required (just delete the zones form the xml save)_
=> resolved #336 by fixing my oversight and deleating the Zone on despawn

Patches/Drill patches/jewelry.xml
Previously, this was excluding from dq_mki, dq_mkii, and billtypeminer_i. I _think_ the intent was to exclude from all and give them a small chance, based on tier, of getting those valuable gemstone ores (I inferred this from the miners XML). If so, this is a good patch to do so. If I misunderstood the intent, it is not. Let me know and I can correct this patch and resubmit.
Also of note, `starts-with(defName, "PRF_DeepQuarry_mk") or defName="PRF_BillTypeMiner_I"` lets you save 3 `PatchOperationAdd` nodes. Not going to have much performance impact but applied to a large enough patching project, the pattern could add up.
Also, let me know if the "no newline at end of file" is an explicit standard or just happenstance. I can follow it with a couple of changes.
=> Fixes to jewelry patch

Source/ProjectRimFactory/Common/GatherThingsUtility.cs
Noticed smart hoppers were picking stuff up from underground belts, so some items would be instantly taken back after going through a puller. This was an issue when `PickupFromGround` was enabled.
Video:
https://user-images.githubusercontent.com/29930410/111091404-983ced00-8511-11eb-8a65-119311d7e228.mp4
Added a check for skipping items in underground belts and over-underground connectors.
Also reformatted the `GatherThingsUtility` file a bit if that's okay.
=> Fix hoppers pulling from underground belts

Defs/ThingDefs_Buildings/Buildings_Drones.xml, Source/ProjectRimFactory/Drones/Building_DroneStation.cs
resolves #196 
@zymex22 if the goal was to have this as a setting in XML please let me know and i will add this.
ATM adds a general 10W per drone for any station.
Ready for merge if nothing additional is required
=> #196 Added 10W Power Consumption per Drone

Source/ProjectRimFactory/Drones/Building_DroneStation.cs
resolves #415
resolves #340 
Hides the Zones & prevent's the player from interacting with them by setting Mutable only to True when it is needed
@zymex22 Ready for merge after testing.
=> #415 #340 Only sets Zones as Mutable when they are deleated

Defs/ThingDefs_Buildings/Buildings_Storage.xml, Languages/English/Keyed/AllKeyed_Settings.xml, Source/ProjectRimFactory/AutoMachineTool/Building_Base.cs, Source/ProjectRimFactory/Common/IPRF_Building.cs, Source/ProjectRimFactory/Common/ITab_ProductionSettings.cs, Source/ProjectRimFactory/Common/PRF_Building.cs, Source/ProjectRimFactory/Storage/Building_ItemSlide.cs
resolves #347
adds a Checkbox in the the Settings tab of all `IPRF_Building`s to forbid the item on placement.
This affects:
- Belts
- Pullers
- item Chute
- Assemblers
_maybe more if we add the tab for them_
@zymex22 please test before merge.
=> #347 added setting to forbid on placemement for all IPRF_Building(s)

Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs
A typo was likely causing NullReferenceException errors in my game.
This fix was not tested beyond "hey the NullReferenceException errors disappeared afterwards".
=> Fix typo in Building_StorageUnitIOPort.cs

Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs, Source/ProjectRimFactory/Storage/UI/Dialog_OutputMinMax.cs
In the old code, if outputMin > outputMax in setting, IO port would never update, even if useMin and/or useMax isn't enabled.
This fix adds additional checks for if useMin and useMax are both enabled before checking if outputMin > outputMax.
=> Fix case of IOPort not updating

Patches/RimFridge.xml, Patches/SimpleFridge.xml
resolves #532 
Copy and Paste patch of the Rimfridge version.
@zymex22 I left the Def names the same, that should enable users to switch between the two.
however i would expect issue if they are used together.
_Is there a way to ensure that only one patch will trigger if both mods are installed?_
On the other hand it makes no sense to have both of them installed at the same time.
=> #532 Added Patch for Simple Fridge

Defs/RecipeDefs/Recipes_Items.xml
Also a bit of labeling.  Somebody contacted me about this wondering why the hell they couldn't progress to Tier 2.
Basic AI Chips are required for assembling the research bench, but in all the production recipes they're labeled as "Weak AI Chips" which is probably some kind of legacy holdover from a different name.  So as far as they could tell there was no way to make the thing they needed, because presumably "Basic" is better than "Weak", and they were under the assumption "Weak AI Chips" were some kind of Tier 0.5.
=> Fix inconsistent name of Chip Tier 1

Defs/TraderKindDefs/Orbital_TraderKinds.xml
Label now uses standard all-lower-case syntax.
Comparing PRF and stock trade ship:
Closes zymex22/Project-RimFactory-Revived#558.
=> Update trader label

Languages/English/Keyed/AllKeyed_SAL3.xml, Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
=> #577 added check if cells are blocked

Patches/Drill patches/OrientalDragonMOD.xml
Based on the WhatTheHack patch.  "Syulipia_Gate_Dragon" was being taken as a valid ore to be mined, and so it would either obliterate the miner as someone mentioned or it would straight-up crash the game if you used the highest tier miner to create one using a bill deliberately.
=> Patch for Oriental Dragon mod.

Patches/Food_Patches/VGP_Gourmet.xml
Resolves #648 
Changes as follows:
- MakePolenta -> Bakepolenta
- MakebulkPolenta -> GrillPolenta 
GrillPolenta is removed because this is on the Electric Stove rather than the VGP specific Oven so it's inherited correctly.
- CraftCornmeal
- CraftBulkCornmeal
Corn is now used directly as raw corn
- GroundSugar
- CraftBulkSugar
Sugar is now used directly as sugarcane
- BakeCornbread
Gone.  Corn grinds into Flour now.
=> Replace VGP Gourmet Patch

Source/ProjectRimFactory/AutoMachineTool/Building_BaseRange.cs, Source/ProjectRimFactory/AutoMachineTool/Building_BeltConveyor.cs, Source/ProjectRimFactory/AutoMachineTool/Building_BeltSplitter.cs, Source/ProjectRimFactory/Common/PRFMapComponent.cs
Needs some Testing.
Improves Performance by Optimizing the use of the `OutputBeltAt` Function
The Function was always used with the Same Parameter `OutputCell()` Since that value only changes when the Building is Placed, that means that it can be cached. Clearing the cache only when it is moved.
_may need to check if the cache is cleared on reinstall_
_should we ever add a rotate after placement, that would need to clear aswell_
**Note: the numbers are misleading due to the use of profiling the Type. Actual load is much lower in both cases**
Before
After
=> (experimental) improved belt performance

Source/ProjectRimFactory/Common/HarmonyPatches/PatchStorage.cs
resolves #678 
I did some testing and it turns out that
- `System.Linq.Enumerable:Contains`
- `Rimwold.SlotGroup:get_HeldThings`
Only show up on DSU where Allow Pawn Input is set to false.
Further testing showed that the only items affected by that additional check are the items inside the DSU
Removing the check appears to have no side effect.
The load of the **removed** calls was based on the amount of items in the DSU and the count of DSU's.
For the Screenshot this more then halves the impact.
=> #678 removed unnecessary checks

Source/ProjectRimFactory/AutoMachineTool/SAL_TargetBench.cs, Source/ProjectRimFactory/SAL3/Tools/ProjectSAL_Utilities.cs
resolves #684 
also Ensured SAL and Assemblers use the same Calc code
=> #684 fixed Dominant Ingrediant Calc

Source/ProjectRimFactory/AutoMachineTool/Building_Base.cs, Source/ProjectRimFactory/Common/HarmonyPatches/Patch_GenRecipe_MakeRecipeProducts.cs, Source/ProjectRimFactory/Common/PRF_Building.cs, Source/ProjectRimFactory/SAL3/Things/Assemblers/Building_ProgrammableAssembler.cs
=> #310 now highlights output stockpile if it can use it entierly

Source/ProjectRimFactory/AutoMachineTool/Building_BeltSplitter.cs, Source/ProjectRimFactory/AutoMachineTool/ITab_ConveyorFilter.cs
resolves #452 
Only deactivates Output if they are used as an Input
fixed GUI Input Detection for Splitters
=> Resolved issues with Splitters linking into eachother

Source/ProjectRimFactory/SAL3/Things/ITab_RecipeHolder.cs
=> Added a Search Bar to recipe database

Defs/RecipeDefs/Recipes_Recycle.xml, Patches/Biotech.xml
resolves #664 
Adds a Bill that consumes 8 Neutroamine to destroy a Wastepack.
It is faster than the Vanilla Option but not too fast
=> Excluded Wastepack from Destroy Anything and Added alternative

Source/ProjectRimFactory/Common/PRF_CustomizeDefs.cs, Source/ProjectRimFactory/Common/ProjectRimFactory_ModComponent.cs
=> Added support for Research Tree (Continued)

Source/ProjectRimFactory/SAL3/Things/Building_RecipeHolder.cs
resolves #804 by removing null Recipes
=> Prevent RecipeDB Null ref when Removing Mods with saved Bills

Source/ProjectRimFactory/AutoMachineTool/GenRecipe2.cs
Closing #823 
resolved issue by commenting out unused cod path
I'm Commenting the Code out instead of removing it to help future me correlate it better the the Vanilla function that it replicates.
This should aid in future updates
=> Fixed Null Ref wehen crafting items with NULL Quality

Languages/English/Keyed/AllKeyed_Settings.xml, Source/ProjectRimFactory/Common/CompTransmitsPower.cs, Source/ProjectRimFactory/Common/ProjectRimFactory_ModSettings.cs
=> Switched to hidden Cable for Belts (with disable Setting)
